### PR TITLE
Functional typescript codelab

### PR DESCRIPTION
**Pull request by mrmeku**

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]
all the formatting changes obscure the actual delta a bit

**Comment by mrmeku** [comment]
Addressed the formatting changes. Sorry about those, I always forget that my editor does that by default

**Comment by mrmeku** [comment]
Also added a webpack devserver

**Review by alexeagle — APPROVED** [review]
@benjaminp want to merge?

Thanks @mrmeku want to invoice the rules authors SIG for your time?

**Comment by benjaminp** [comment]
Thanks for the ping—evidently I did not have notifications on this repo. BTW, I was mostly working off the `updates` branch. Maybe you can figure out the merge, there?

**Pull request merged**
